DROP DATABASE IF EXISTS zoo;

CREATE DATABASE zoo 
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE zoo;

CREATE TABLE IF NOT EXISTS chat (
    id INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL,
    yeux VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;
